
services:
  postgres_msk:
    container_name: postgres_msk
    image: postgres:17.2
    # change permission of the directory /var/lib/postgresql/data to 0700
    #   - 0700: owner, the postgres user in this case - full permission
    #   - full permission: read, write, execute
    #   - /var/lib/postgresql/data: default directory where postgres stores its data
    command: > 
      bash -c "chmod -R 0700 /var/lib/postgresql/data &&docker-entrypoint.sh ${POSTGRES_USER}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init_scripts:/docker-entrypoint-initdb.d:rw
    ports:
      - "5434:5434"
    networks:
      - postgres_network_msk
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: no
  pgadmin_msk:
    container_name: pgadmin_msk
    image: dpage/pgadmin4:8.14.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5435:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_msk
    networks:
      - postgres_network_msk
    restart: no

networks:
  postgres_network_msk:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: